### ISSUE TITLE
Compatibility issues in both v12 but also DnD5e 3.1.2 (and I assume 3.2.0)

### ISSUE THREAD

**Issue by GambetTV** [mhilbrunner/token-hud-wildcard#2]
All right, so on one PC I am running v11.315 with DnD5e 3.1.2, and this module still works fine, but I have noticed that you can no longer choose a Wildcard Drop Default image. The setting doesn't even show up anymore. However, if a token has already had a drop default image set, it still acts as if that image is the default, there's simply no way to change it.

On my other PC I'm running a test version of v12 with DnD5e 3.2.0, and for some reason that one behaves differently. The Wildcard Drop Default option exists, and if you set it, it even works. However, the rest of the module does not really work at all. When you right click a token you still see the button to change images, and those images even show up and you can scroll through them, but clicking on an image doesn't do anything. There are no console errors, just nothing happens.

I understand that this module isn't updated very often. I don't expect you to fix the v11 version, as it still basically works, it just has one minor bug. But if we could at some point get v12 support that would be great. It seems like it's 99% there to working, there's just some kind of bug to be ironed out.

Thanks!

**Comment by mhilbrunner** [comment]
@GambetTV I just released version [2.0.0](https://github.com/mhilbrunner/token-hud-wildcard/releases/tag/2.0.0), freshly resurrected out of maintenance mode. In my testing, this should now work both with latest Foundry v12 and the latest 5E system version.

I even added two small new features :) Please ping me if you run into any issues!

**Comment by GambetTV** [comment]
@mhilbrunner This looks pretty good! There is one major thing that no longer works, which is quite vital to my purposes: adding _scaleX_ to the filename no longer changes the scale.

Also, the two new features are both very cool, but I wonder how much of a pain would it be to turn them into options we could turn on or off in the settings?

**Comment by mhilbrunner** [comment]
Ah, I'll test the scale, good catch. Making them options would be easy, will do.

**Comment by mhilbrunner** [comment]
@GambetTV Please test [2.1.0](https://github.com/mhilbrunner/token-hud-wildcard/releases/tag/2.1.0), width/height/scale should now be settable from file names once again, please let me know if there still is an issue for you.

Also added settings for each of the new right click behaviours, so you can disable those :)

**Comment by GambetTV** [comment]
Works like a dream. Thank you so much!
